kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      auto_tag: true
      repo: docker.digitaloctave.com/drone-python-example
      registry: docker.digitaloctave.com
